services:
  rabbitmq:
    image: rabbitmq:4.0.2
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./backend/.env
    networks:
      - app-network 

  mongo:
    image: mongo:5.0
    container_name: mongocontainer
    ports:
      - "27017:27017"
    env_file:
      - ./backend/.env
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  nodejs-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nodejs-container
    env_file:
      - ./backend/.env
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge